/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => StudentActivityPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var MODEL_OPTIONS = {
  openai: [
    // GPT-5 Series (Reasoning Models)
    { id: "gpt-5", name: "GPT-5 (Reasoning)" },
    { id: "gpt-5-mini", name: "GPT-5 Mini (Reasoning)" },
    { id: "gpt-5-nano", name: "GPT-5 Nano (Reasoning)" },
    // GPT-4o Series
    { id: "gpt-4o", name: "GPT-4o" },
    { id: "gpt-4o-mini", name: "GPT-4o Mini" },
    // GPT-4 Series
    { id: "gpt-4-turbo", name: "GPT-4 Turbo" },
    { id: "gpt-4", name: "GPT-4" },
    // Legacy
    { id: "gpt-3.5-turbo", name: "GPT-3.5 Turbo" }
  ],
  claude: [
    // Claude 4.x Series (Latest)
    { id: "claude-sonnet-4-5-20250929", name: "Claude Sonnet 4.5 (Recommended)" },
    { id: "claude-opus-4-1-20250805", name: "Claude Opus 4.1" },
    { id: "claude-opus-4-20250514", name: "Claude Opus 4" },
    { id: "claude-sonnet-4-20250514", name: "Claude Sonnet 4" },
    { id: "claude-haiku-4-5-20251001", name: "Claude Haiku 4.5" },
    // Claude 3.7 Series
    { id: "claude-3-7-sonnet-20250219", name: "Claude 3.7 Sonnet" },
    // Claude 3.5 Series
    { id: "claude-3-5-sonnet-20241022", name: "Claude 3.5 Sonnet" },
    { id: "claude-3-5-haiku-20241022", name: "Claude 3.5 Haiku (Fastest)" },
    // Claude 3 Series (Legacy)
    { id: "claude-3-opus-20240229", name: "Claude 3 Opus" },
    { id: "claude-3-haiku-20240307", name: "Claude 3 Haiku" }
  ],
  gemini: [
    // Gemini 2.5 Series (Latest)
    { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash (Stable)" },
    { id: "gemini-2.5-flash-lite", name: "Gemini 2.5 Flash Lite" },
    // Gemini 2.0 Series
    { id: "gemini-2.0-flash", name: "Gemini 2.0 Flash" },
    { id: "gemini-2.0-flash-preview-image-generation", name: "Gemini 2.0 Flash (Image Gen)" },
    // Gemini 1.5 Series
    { id: "gemini-1.5-pro", name: "Gemini 1.5 Pro" },
    { id: "gemini-1.5-flash", name: "Gemini 1.5 Flash" },
    { id: "gemini-1.5-flash-8b", name: "Gemini 1.5 Flash 8B" }
  ],
  grok: [
    // Grok 4.x Series (Latest)
    { id: "grok-4-0709", name: "Grok 4" },
    { id: "grok-4-1-fast", name: "Grok 4.1 Fast (Recommended)" },
    { id: "grok-4-1-fast-non-reasoning", name: "Grok 4.1 Fast (Non-Reasoning)" },
    // Grok 3 Series
    { id: "grok-3", name: "Grok 3" },
    { id: "grok-3-mini", name: "Grok 3 Mini" },
    // Grok Code
    { id: "grok-code-fast-1", name: "Grok Code Fast" },
    // Grok 2 Series (Legacy)
    { id: "grok-2-vision-1212", name: "Grok 2 Vision" },
    { id: "grok-2-image-1212", name: "Grok 2 Image" }
  ]
};
var DEFAULT_MODELS = {
  openai: "gpt-4o-mini",
  claude: "claude-sonnet-4-5-20250929",
  gemini: "gemini-2.5-flash",
  grok: "grok-4-1-fast"
};
var DEFAULT_SETTINGS = {
  apiProvider: "openai",
  apiKey: "",
  targetCharCount: 500,
  outputFolder: "",
  modelId: "gpt-4o-mini"
};
function countChars(text) {
  return text.length;
}
function countBytes(text) {
  let bytes = 0;
  for (let i = 0; i < text.length; i++) {
    const char = text.charAt(i);
    if (char === "\n") {
      bytes += 1;
    } else if (escape(char).length > 4) {
      bytes += 3;
    } else {
      bytes += 1;
    }
  }
  return bytes;
}
function estimateBytes(charCount) {
  return Math.round(charCount * 0.8 * 3 + charCount * 0.2 * 1);
}
function parseTSV(data) {
  const lines = data.trim().split("\n");
  const activities = [];
  for (const line of lines) {
    const parts = line.split("\t");
    if (parts.length >= 3) {
      activities.push({
        studentId: parts[0].trim(),
        studentName: parts[1].trim(),
        activityContent: parts.slice(2).join(" ").trim()
      });
    }
  }
  return activities;
}
function generateMarkdownTable(records) {
  let table = "| \uD559\uBC88 | \uC131\uBA85 | \uD559\uC0DD\uD65C\uB3D9\uAE30\uB85D | \uAD50\uC0AC\uAD00\uCC30\uAE30\uB85D | \uAE00\uC790 \uC218 | \uBC14\uC774\uD2B8 \uC218 |\n";
  table += "|------|------|-------------|-------------|---------|----------|\n";
  for (const record of records) {
    const escapedActivity = record.activityContent.replace(/\|/g, "\\|").replace(/\n/g, " ");
    const escapedObservation = record.observation.replace(/\|/g, "\\|").replace(/\n/g, " ");
    table += `| ${record.studentId} | ${record.studentName} | ${escapedActivity} | ${escapedObservation} | ${record.charCount} | ${record.byteCount} |\n`;
  }
  return table;
}
function generateTSVData(records) {
  let tsv = "\uD559\uBC88\t\uC131\uBA85\t\uD559\uC0DD\uD65C\uB3D9\uAE30\uB85D\t\uAD50\uC0AC\uAD00\uCC30\uAE30\uB85D\t\uAE00\uC790 \uC218\t\uBC14\uC774\uD2B8 \uC218\n";
  for (const record of records) {
    const cleanActivity = record.activityContent.replace(/[\t\n\r]/g, " ");
    const cleanObservation = record.observation.replace(/[\t\n\r]/g, " ");
    tsv += `${record.studentId}\t${record.studentName}\t${cleanActivity}\t${cleanObservation}\t${record.charCount}\t${record.byteCount}\n`;
  }
  return tsv;
}
var SYSTEM_PROMPT = `\uB2F9\uC2E0\uC740 \uD559\uC0DD\uC744 \uAE4A\uC774 \uC774\uD574\uD558\uACE0 \uC560\uC815\uC744 \uAC00\uC9C0\uACE0 \uAD00\uCC30\uD558\uB294 \uD55C\uAD6D \uACE0\uB4F1\uD559\uAD50 \uB2F4\uC784\uAD50\uC0AC\uC785\uB2C8\uB2E4.
\uD559\uC0DD\uC758 \uD65C\uB3D9 \uB0B4\uC6A9\uC744 \uBC14\uD0D5\uC73C\uB85C \uAD50\uC0AC \uAD00\uCC30 \uAE30\uB85D\uC744 \uC791\uC131\uD574\uC8FC\uC138\uC694.

[\uD575\uC2EC \uC6D0\uCE59]
- \uC778\uACF5\uC9C0\uB2A5\uC774 \uC791\uC131\uD55C \uAC83\uC774 \uC544\uB2CC, \uAD50\uC0AC\uAC00 \uD559\uC0DD\uC744 \uC9C1\uC811 \uAD00\uCC30\uD558\uACE0 \uC560\uC815\uC744 \uB2F4\uC544 \uC791\uC131\uD55C \uAE30\uB85D\uCC98\uB7FC \uBCF4\uC5EC\uC57C \uD569\uB2C8\uB2E4
- \uD559\uC0DD\uC758 \uAC15\uC810, \uB178\uB825, \uC131\uC7A5 \uACFC\uC815\uC744 \uB530\uB73B\uD558\uAC8C \uC11C\uC220\uD569\uB2C8\uB2E4
- \uAC1D\uAD00\uC801 \uC0AC\uC2E4\uC5D0 \uAE30\uBC18\uD558\uB418, \uAD50\uC0AC\uC758 \uAE0D\uC815\uC801 \uAD00\uC810\uC744 \uB2F4\uC2B5\uB2C8\uB2E4

[\uBB38\uCCB4 \uADDC\uCE59]
- \uC11C\uC220\uD615 \uC885\uACB0\uC5B4\uBBF8 \uC0AC\uC6A9: "~\uD568", "~\uC784", "~\uB0A8", "~\uBCF4\uC784", "~\uB4DC\uB7EC\uB0C4"
- \uC81C\uBAA9, \uBA38\uB9AC\uB9D0, \uD559\uC0DD \uC774\uB984 \uD3EC\uD568 \uAE08\uC9C0
- 3\uC778\uCE6D \uAD00\uCC30\uC790 \uC2DC\uC810\uC73C\uB85C \uC791\uC131
- \uD55C \uBB38\uB2E8\uC73C\uB85C \uC790\uC5F0\uC2A4\uB7FD\uAC8C \uC774\uC5B4\uC9C0\uB3C4\uB85D \uC791\uC131

[\uB0B4\uC6A9 \uAD6C\uC131]
1. \uD65C\uB3D9\uC758 \uAD6C\uCCB4\uC801 \uB9E5\uB77D\uACFC \uCC38\uC5EC \uC591\uC0C1
2. \uD559\uC0DD\uC774 \uBCF4\uC5EC\uC900 \uC5ED\uB7C9\uC774\uB098 \uD0DC\uB3C4
3. \uD65C\uB3D9\uC744 \uD1B5\uD55C \uC131\uC7A5\uC774\uB098 \uBC1C\uC804 \uAC00\uB2A5\uC131

[\uD53C\uD574\uC57C \uD560 \uD45C\uD604]
- AI, VR, AR \uB4F1 \uC601\uBB38 \uC57D\uC5B4 \u2192 \uC778\uACF5\uC9C0\uB2A5, \uAC00\uC0C1\uD604\uC2E4, \uC99D\uAC15\uD604\uC2E4 \uC0AC\uC6A9
- \uACFC\uB3C4\uD55C \uC218\uC2DD\uC5B4\uB098 \uBE48 \uCE6D\uCC2C
- \uBAA8\uB4E0 \uD559\uC0DD\uC5D0\uAC8C \uC801\uC6A9 \uAC00\uB2A5\uD55C \uC77C\uBC18\uC801\uC778 \uD45C\uD604
- \uAE30\uACC4\uC801\uC774\uAC70\uB098 \uC815\uD615\uD654\uB41C \uBB38\uC7A5 \uD328\uD134

[\uC88B\uC740 \uC608\uC2DC \uD45C\uD604]
- "\uD0D0\uAD6C \uACFC\uC815\uC5D0\uC11C \uAF3C\uAF3C\uD55C \uC790\uB8CC \uC870\uC0AC\uC640 \uB17C\uB9AC\uC801 \uBD84\uC11D\uB825\uC744 \uBCF4\uC5EC\uC90C"
- "\uBAA8\uB460 \uD65C\uB3D9 \uC2DC \uB2E4\uC591\uD55C \uC758\uACAC\uC744 \uC874\uC911\uD558\uBA70 \uD611\uB825\uC801 \uD0DC\uB3C4\uB85C \uCC38\uC5EC\uD568"
- "\uC2A4\uC2A4\uB85C \uBB38\uC81C\uB97C \uBC1C\uACAC\uD558\uACE0 \uD574\uACB0\uCC45\uC744 \uBAA8\uC0C9\uD558\uB294 \uC790\uAE30\uC8FC\uB3C4\uC801 \uD559\uC2B5 \uC5ED\uB7C9\uC744 \uAC16\uCDA4"

[\uCD9C\uB825 \uD615\uC2DD]
- \uCD94\uAC00 \uC124\uBA85\uC774\uB098 \uBA38\uB9AC\uB9D0 \uC5C6\uC774 \uAD50\uC0AC\uAD00\uCC30\uAE30\uB85D \uBCF8\uBB38\uB9CC \uCD9C\uB825
- \uC790\uC5F0\uC2A4\uB7EC\uC6B4 \uD55C \uBB38\uB2E8\uC73C\uB85C \uAD6C\uC131`;
async function callOpenAI(apiKey, modelId, activity, targetCharCount) {
  const userPrompt = `[\uC81C\uC57D \uC870\uAC74]
- \uBAA9\uD45C \uAE00\uC790 \uC218: ${targetCharCount}\uC790 (\xB110%)

[\uC785\uB825]
\uD559\uBC88: ${activity.studentId}
\uC774\uB984: ${activity.studentName}
\uD65C\uB3D9\uB0B4\uC6A9: ${activity.activityContent}

[\uCD9C\uB825]
\uAD50\uC0AC\uAD00\uCC30\uAE30\uB85D\uB9CC \uCD9C\uB825 (\uCD94\uAC00 \uC124\uBA85 \uC5C6\uC774)`;
  const response = await (0, import_obsidian.requestUrl)({
    url: "https://api.openai.com/v1/chat/completions",
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`
    },
    body: JSON.stringify({
      model: modelId,
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        { role: "user", content: userPrompt }
      ],
      max_tokens: 2e3,
      temperature: 0.7
    })
  });
  if (response.status !== 200) {
    throw new Error(`OpenAI API \uC624\uB958: ${response.status}`);
  }
  return response.json.choices[0].message.content.trim();
}
async function callClaude(apiKey, modelId, activity, targetCharCount) {
  const userPrompt = `[\uC81C\uC57D \uC870\uAC74]
- \uBAA9\uD45C \uAE00\uC790 \uC218: ${targetCharCount}\uC790 (\xB110%)

[\uC785\uB825]
\uD559\uBC88: ${activity.studentId}
\uC774\uB984: ${activity.studentName}
\uD65C\uB3D9\uB0B4\uC6A9: ${activity.activityContent}

[\uCD9C\uB825]
\uAD50\uC0AC\uAD00\uCC30\uAE30\uB85D\uB9CC \uCD9C\uB825 (\uCD94\uAC00 \uC124\uBA85 \uC5C6\uC774)`;
  const response = await (0, import_obsidian.requestUrl)({
    url: "https://api.anthropic.com/v1/messages",
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-api-key": apiKey,
      "anthropic-version": "2023-06-01"
    },
    body: JSON.stringify({
      model: modelId || "claude-3-5-sonnet-20241022",
      max_tokens: 2e3,
      system: SYSTEM_PROMPT,
      messages: [{ role: "user", content: userPrompt }]
    })
  });
  if (response.status !== 200) {
    throw new Error(`Claude API \uC624\uB958: ${response.status}`);
  }
  return response.json.content[0].text.trim();
}
async function callGemini(apiKey, modelId, activity, targetCharCount) {
  const userPrompt = `${SYSTEM_PROMPT}

[\uC81C\uC57D \uC870\uAC74]
- \uBAA9\uD45C \uAE00\uC790 \uC218: ${targetCharCount}\uC790 (\xB110%)

[\uC785\uB825]
\uD559\uBC88: ${activity.studentId}
\uC774\uB984: ${activity.studentName}
\uD65C\uB3D9\uB0B4\uC6A9: ${activity.activityContent}

[\uCD9C\uB825]
\uAD50\uC0AC\uAD00\uCC30\uAE30\uB85D\uB9CC \uCD9C\uB825 (\uCD94\uAC00 \uC124\uBA85 \uC5C6\uC774)`;
  const response = await (0, import_obsidian.requestUrl)({
    url: `https://generativelanguage.googleapis.com/v1beta/models/${modelId || "gemini-1.5-flash"}:generateContent?key=${apiKey}`,
    method: "POST",
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      contents: [
        {
          parts: [{ text: userPrompt }]
        }
      ],
      generationConfig: {
        temperature: 0.7,
        maxOutputTokens: 2e3
      }
    })
  });
  if (response.status !== 200) {
    throw new Error(`Gemini API \uC624\uB958: ${response.status}`);
  }
  return response.json.candidates[0].content.parts[0].text.trim();
}
async function callGrok(apiKey, modelId, activity, targetCharCount) {
  const userPrompt = `[\uC81C\uC57D \uC870\uAC74]
- \uBAA9\uD45C \uAE00\uC790 \uC218: ${targetCharCount}\uC790 (\xB110%)

[\uC785\uB825]
\uD559\uBC88: ${activity.studentId}
\uC774\uB984: ${activity.studentName}
\uD65C\uB3D9\uB0B4\uC6A9: ${activity.activityContent}

[\uCD9C\uB825]
\uAD50\uC0AC\uAD00\uCC30\uAE30\uB85D\uB9CC \uCD9C\uB825 (\uCD94\uAC00 \uC124\uBA85 \uC5C6\uC774)`;
  const response = await (0, import_obsidian.requestUrl)({
    url: "https://api.x.ai/v1/chat/completions",
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`
    },
    body: JSON.stringify({
      model: modelId || "grok-3-fast",
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        { role: "user", content: userPrompt }
      ],
      max_tokens: 2e3,
      temperature: 0.7
    })
  });
  if (response.status !== 200) {
    throw new Error(`Grok API \uC624\uB958: ${response.status}`);
  }
  return response.json.choices[0].message.content.trim();
}
var InputModal = class extends import_obsidian.Modal {
  constructor(app, plugin, onSubmit) {
    super(app);
    this.inputData = "";
    this.plugin = plugin;
    this.targetCharCount = plugin.settings.targetCharCount;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("student-activity-modal");
    contentEl.createEl("h2", { text: "\uD559\uC0DD\uD65C\uB3D9 \u2192 \uAD50\uC0AC\uAD00\uCC30\uAE30\uB85D \uBCC0\uD658" });
    contentEl.createEl("p", {
      text: "\uAD6C\uAE00 \uC2A4\uD504\uB808\uB4DC\uC2DC\uD2B8\uC5D0\uC11C \uBCF5\uC0AC\uD55C \uB370\uC774\uD130\uB97C \uBD99\uC5EC\uB123\uC73C\uC138\uC694. (\uD559\uBC88 \uD0ED \uC774\uB984 \uD0ED \uD65C\uB3D9\uB0B4\uC6A9)",
      cls: "student-activity-description"
    });
    const textAreaContainer = contentEl.createDiv({ cls: "student-activity-textarea-container" });
    const textArea = textAreaContainer.createEl("textarea", {
      cls: "student-activity-textarea",
      attr: { rows: "10", placeholder: "10101\t\uAE40\uCCA0\uC218\t\uD504\uB85C\uC81D\uD2B8 \uD65C\uB3D9\uC5D0\uC11C \uB9AC\uB354 \uC5ED\uD560\uC744 \uB9E1\uC544...\n10102\t\uC774\uC601\uD76C\t\uD1A0\uB860 \uC218\uC5C5\uC5D0\uC11C \uC801\uADF9\uC801\uC73C\uB85C \uCC38\uC5EC\uD558\uC5EC..." }
    });
    textArea.addEventListener("input", (e) => {
      this.inputData = e.target.value;
      this.updatePreview();
    });
    const previewContainer = contentEl.createDiv({ cls: "student-activity-preview" });
    previewContainer.createEl("h4", { text: "\uC785\uB825 \uB370\uC774\uD130 \uBBF8\uB9AC\uBCF4\uAE30" });
    const previewContent = previewContainer.createDiv({ cls: "student-activity-preview-content" });
    previewContent.setText("\uB370\uC774\uD130\uB97C \uC785\uB825\uD558\uBA74 \uC5EC\uAE30\uC5D0 \uBBF8\uB9AC\uBCF4\uAE30\uAC00 \uD45C\uC2DC\uB429\uB2C8\uB2E4.");
    const charCountContainer = contentEl.createDiv({ cls: "student-activity-char-count" });
    new import_obsidian.Setting(charCountContainer).setName("\uBAA9\uD45C \uAE00\uC790 \uC218").setDesc("\uC0DD\uC131\uB420 \uAD50\uC0AC\uAD00\uCC30\uAE30\uB85D\uC758 \uBAA9\uD45C \uAE00\uC790 \uC218\uB97C \uC124\uC815\uD569\uB2C8\uB2E4.").addText((text) => {
      text.setValue(String(this.targetCharCount)).onChange((value) => {
        const num = parseInt(value);
        if (!isNaN(num) && num > 0) {
          this.targetCharCount = num;
          this.updateByteEstimate();
        }
      });
      text.inputEl.type = "number";
      text.inputEl.min = "100";
      text.inputEl.max = "2000";
    });
    const byteEstimateEl = charCountContainer.createDiv({ cls: "student-activity-byte-estimate" });
    byteEstimateEl.setText(`\uC608\uC0C1 \uBC14\uC774\uD2B8 \uC218: ${estimateBytes(this.targetCharCount)} \uBC14\uC774\uD2B8`);
    const buttonContainer = contentEl.createDiv({ cls: "modal-button-container" });
    const cancelBtn = buttonContainer.createEl("button", {
      text: "\uCDE8\uC18C",
      cls: "student-activity-cancel-btn"
    });
    cancelBtn.addEventListener("click", () => {
      this.close();
    });
    const submitBtn = buttonContainer.createEl("button", {
      text: "\uAD50\uC0AC\uAD00\uCC30\uAE30\uB85D \uC0DD\uC131",
      cls: "mod-cta student-activity-submit-btn"
    });
    submitBtn.addEventListener("click", () => {
      if (!this.inputData.trim()) {
        new import_obsidian.Notice("\uB370\uC774\uD130\uB97C \uC785\uB825\uD574\uC8FC\uC138\uC694.");
        return;
      }
      const activities = parseTSV(this.inputData);
      if (activities.length === 0) {
        new import_obsidian.Notice("\uC720\uD6A8\uD55C \uB370\uC774\uD130\uAC00 \uC5C6\uC2B5\uB2C8\uB2E4. \uD615\uC2DD: \uD559\uBC88 [\uD0ED] \uC774\uB984 [\uD0ED] \uD65C\uB3D9\uB0B4\uC6A9");
        return;
      }
      this.onSubmit(this.inputData, this.targetCharCount);
      this.close();
    });
  }
  updatePreview() {
    const previewContent = this.contentEl.querySelector(".student-activity-preview-content");
    if (!previewContent)
      return;
    const activities = parseTSV(this.inputData);
    if (activities.length === 0) {
      previewContent.setText("\uC720\uD6A8\uD55C \uB370\uC774\uD130\uAC00 \uC5C6\uC2B5\uB2C8\uB2E4. \uD615\uC2DD: \uD559\uBC88 \uD0ED \uC774\uB984 \uD0ED \uD65C\uB3D9\uB0B4\uC6A9");
      return;
    }
    let preview = `\uCD1D ${activities.length}\uBA85\uC758 \uD559\uC0DD \uB370\uC774\uD130:\n\n`;
    for (const activity of activities.slice(0, 5)) {
      preview += `- ${activity.studentId} ${activity.studentName}: ${activity.activityContent.substring(0, 50)}...\n`;
    }
    if (activities.length > 5) {
      preview += `\n... \uC678 ${activities.length - 5}\uBA85`;
    }
    previewContent.setText(preview);
  }
  updateByteEstimate() {
    const byteEstimateEl = this.contentEl.querySelector(".student-activity-byte-estimate");
    if (byteEstimateEl) {
      byteEstimateEl.setText(`\uC608\uC0C1 \uBC14\uC774\uD2B8 \uC218: ${estimateBytes(this.targetCharCount)} \uBC14\uC774\uD2B8`);
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var ProgressModal = class extends import_obsidian.Modal {
  constructor(app) {
    super(app);
    this.progressText = null;
    this.progressBar = null;
    this.progressBarFill = null;
    this.progressPercentText = null;
    this.statusText = null;
    this.studentListContainer = null;
    this.currentIndex = 0;
    this.totalCount = 0;
    this.completedStudents = [];
    this.previousStudentName = "";
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("student-activity-progress-modal");
    const headerDiv = contentEl.createDiv({ cls: "progress-header" });
    const iconSpan = headerDiv.createSpan({ cls: "progress-icon" });
    iconSpan.innerHTML = "\u2728";
    headerDiv.createEl("h2", { text: "\uAD50\uC0AC\uAD00\uCC30\uAE30\uB85D \uC0DD\uC131 \uC911" });
    this.progressText = contentEl.createEl("p", { cls: "progress-text" });
    this.progressText.setText("AI \uBCC0\uD658 \uC900\uBE44 \uC911...");
    const progressWrapper = contentEl.createDiv({ cls: "progress-wrapper" });
    const circleContainer = progressWrapper.createDiv({ cls: "progress-circle-container" });
    this.progressPercentText = circleContainer.createDiv({ cls: "progress-circle" });
    this.progressPercentText.setText("0%");
    const barSection = progressWrapper.createDiv({ cls: "progress-bar-section" });
    const progressBarContainer = barSection.createDiv({ cls: "progress-bar-container" });
    this.progressBar = progressBarContainer.createDiv({ cls: "progress-bar-bg" });
    this.progressBarFill = this.progressBar.createDiv({ cls: "progress-bar-fill" });
    this.progressBarFill.style.width = "0%";
    this.statusText = barSection.createEl("p", { cls: "progress-status" });
    this.statusText.setText("\uC7A0\uC2DC\uB9CC \uAE30\uB2E4\uB824\uC8FC\uC138\uC694...");
    const listSection = contentEl.createDiv({ cls: "progress-list-section" });
    listSection.createEl("h4", { text: "\uD83D\uDCDD \uBCC0\uD658 \uC644\uB8CC" });
    this.studentListContainer = listSection.createDiv({ cls: "progress-student-list" });
    const infoText = contentEl.createEl("p", { cls: "progress-info" });
    infoText.innerHTML = "\uD83E\uDD16 AI\uAC00 \uD559\uC0DD\uD65C\uB3D9 \uB0B4\uC6A9\uC744 <strong>\uAD50\uC0AC\uAD00\uCC30\uAE30\uB85D \uBB38\uCCB4</strong>\uB85C \uBCC0\uD658\uD558\uACE0 \uC788\uC2B5\uB2C8\uB2E4.";
  }
  updateProgress(current, total, studentName) {
    this.currentIndex = current;
    this.totalCount = total;
    const percentage = Math.round(current / total * 100);
    if (this.progressText) {
      this.progressText.innerHTML = `<span class="current-student">\uD83C\uDFAF ${studentName}</span> \uBCC0\uD658 \uC911... <span class="progress-count">(${current}/${total}\uBA85)</span>`;
    }
    if (this.progressBarFill) {
      this.progressBarFill.style.width = `${percentage}%`;
      if (percentage < 30) {
        this.progressBarFill.style.background = "linear-gradient(90deg, #ff6b6b, #ffa502)";
      } else if (percentage < 70) {
        this.progressBarFill.style.background = "linear-gradient(90deg, #ffa502, #2ed573)";
      } else {
        this.progressBarFill.style.background = "linear-gradient(90deg, #2ed573, #1e90ff)";
      }
    }
    if (this.progressPercentText) {
      this.progressPercentText.setText(`${percentage}%`);
      this.progressPercentText.style.background = `conic-gradient(var(--interactive-accent) ${percentage * 3.6}deg, var(--background-modifier-border) 0deg)`;
    }
    if (this.statusText) {
      if (current === total) {
        this.statusText.innerHTML = "\u2705 \uBCC0\uD658 \uC644\uB8CC! \uACB0\uACFC\uB97C \uC800\uC7A5\uD558\uACE0 \uC788\uC2B5\uB2C8\uB2E4...";
      } else {
        const remaining = total - current;
        const estimatedTime = remaining * 2;
        this.statusText.innerHTML = `\u23F3 \uB0A8\uC740 \uD559\uC0DD: <strong>${remaining}\uBA85</strong> (\uC608\uC0C1 ${estimatedTime}\uCD08)`;
      }
    }
    if (this.previousStudentName && this.studentListContainer) {
      const studentTag = this.studentListContainer.createSpan({ cls: "completed-student-tag" });
      studentTag.setText(`\u2713 ${this.previousStudentName}`);
      this.studentListContainer.scrollTop = this.studentListContainer.scrollHeight;
    }
    this.previousStudentName = studentName;
  }
  // 마지막 학생 완료 처리
  markLastStudentComplete() {
    if (this.previousStudentName && this.studentListContainer) {
      const studentTag = this.studentListContainer.createSpan({ cls: "completed-student-tag" });
      studentTag.setText(`\u2713 ${this.previousStudentName}`);
      this.studentListContainer.scrollTop = this.studentListContainer.scrollHeight;
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var StudentActivitySettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.modelDropdown = null;
    this.plugin = plugin;
  }
  getProviderName(provider) {
    const names = {
      openai: "OpenAI",
      claude: "Anthropic",
      gemini: "Google",
      grok: "xAI"
    };
    return names[provider] || provider;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h1", { text: "\uD559\uC0DD\uD65C\uB3D9 \u2192 \uAD50\uC0AC\uAD00\uCC30\uAE30\uB85D \uBCC0\uD658 \uC124\uC815" });
    new import_obsidian.Setting(containerEl).setName("AI \uC81C\uACF5\uC790").setDesc("\uC0AC\uC6A9\uD560 AI API \uC81C\uACF5\uC790\uB97C \uC120\uD0DD\uD569\uB2C8\uB2E4.").addDropdown((dropdown) => {
      dropdown.addOption("openai", "OpenAI (GPT)");
      dropdown.addOption("claude", "Anthropic (Claude)");
      dropdown.addOption("gemini", "Google (Gemini)");
      dropdown.addOption("grok", "xAI (Grok)");
      dropdown.setValue(this.plugin.settings.apiProvider);
      dropdown.onChange(async (value) => {
        this.plugin.settings.apiProvider = value;
        this.plugin.settings.modelId = DEFAULT_MODELS[value];
        await this.plugin.saveSettings();
        this.display();
      });
    });
    const apiKeyPlaceholders = {
      openai: "sk-...",
      claude: "sk-ant-...",
      gemini: "AIza...",
      grok: "xai-..."
    };
    new import_obsidian.Setting(containerEl).setName("API \uD0A4").setDesc(`${this.getProviderName(this.plugin.settings.apiProvider)} API \uD0A4\uB97C \uC785\uB825\uD569\uB2C8\uB2E4.`).addText(
      (text) => text.setPlaceholder(apiKeyPlaceholders[this.plugin.settings.apiProvider] || "API \uD0A4").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
        this.plugin.settings.apiKey = value;
        await this.plugin.saveSettings();
      })
    );
    const currentProvider = this.plugin.settings.apiProvider;
    const models = MODEL_OPTIONS[currentProvider] || [];
    new import_obsidian.Setting(containerEl).setName("\uBAA8\uB378").setDesc(`${this.getProviderName(currentProvider)}\uC5D0\uC11C \uC0AC\uC6A9\uD560 AI \uBAA8\uB378\uC744 \uC120\uD0DD\uD569\uB2C8\uB2E4.`).addDropdown((dropdown) => {
      this.modelDropdown = dropdown;
      for (const model of models) {
        dropdown.addOption(model.id, model.name);
      }
      const modelExists = models.some((m) => m.id === this.plugin.settings.modelId);
      if (modelExists) {
        dropdown.setValue(this.plugin.settings.modelId);
      } else {
        dropdown.setValue(DEFAULT_MODELS[currentProvider]);
        this.plugin.settings.modelId = DEFAULT_MODELS[currentProvider];
        this.plugin.saveSettings();
      }
      dropdown.onChange(async (value) => {
        this.plugin.settings.modelId = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("\uAE30\uBCF8 \uBAA9\uD45C \uAE00\uC790 \uC218").setDesc("\uAD50\uC0AC\uAD00\uCC30\uAE30\uB85D\uC758 \uAE30\uBCF8 \uBAA9\uD45C \uAE00\uC790 \uC218\uB97C \uC124\uC815\uD569\uB2C8\uB2E4.").addText((text) => {
      text.setPlaceholder("500").setValue(String(this.plugin.settings.targetCharCount)).onChange(async (value) => {
        const num = parseInt(value);
        if (!isNaN(num) && num > 0) {
          this.plugin.settings.targetCharCount = num;
          await this.plugin.saveSettings();
        }
      });
      text.inputEl.type = "number";
    });
    new import_obsidian.Setting(containerEl).setName("\uACB0\uACFC \uC800\uC7A5 \uD3F4\uB354").setDesc("\uBCC0\uD658 \uACB0\uACFC\uB97C \uC800\uC7A5\uD560 \uD3F4\uB354 \uACBD\uB85C (\uBE44\uC6CC\uB450\uBA74 Vault \uB8E8\uD2B8\uC5D0 \uC800\uC7A5)").addText(
      (text) => text.setPlaceholder("\uAD50\uC0AC\uAD00\uCC30\uAE30\uB85D").setValue(this.plugin.settings.outputFolder).onChange(async (value) => {
        this.plugin.settings.outputFolder = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h2", { text: "NEIS \uAE00\uC790\uC218/\uBC14\uC774\uD2B8\uC218 \uACC4\uC0B0 \uAE30\uC900" });
    const infoDiv = containerEl.createDiv({ cls: "student-activity-info" });
    infoDiv.innerHTML = `
      <ul>
        <li><strong>\uAE00\uC790 \uC218</strong>: \uBAA8\uB4E0 \uBB38\uC790\uB97C 1\uAC1C\uB85C \uACC4\uC0B0 (\uD55C\uAE00, \uC601\uBB38, \uC22B\uC790, \uACF5\uBC31, \uD2B9\uC218\uBB38\uC790)</li>
        <li><strong>\uBC14\uC774\uD2B8 \uC218</strong>:
          <ul>
            <li>\uD55C\uAE00, \uD55C\uC790: 3\uBC14\uC774\uD2B8</li>
            <li>\uC601\uBB38, \uC22B\uC790, \uD2B9\uC218\uBB38\uC790, \uACF5\uBC31, \uC904\uBC14\uAFC8: 1\uBC14\uC774\uD2B8</li>
          </ul>
        </li>
      </ul>
    `;
  }
};
var StudentActivityPlugin = class extends import_obsidian.Plugin {
  async onload() {
    console.log("Loading Student Activity to Observation Plugin");
    await this.loadSettings();
    this.addSettingTab(new StudentActivitySettingTab(this.app, this));
    this.addCommand({
      id: "open-conversion-modal",
      name: "\uD559\uC0DD\uD65C\uB3D9 \u2192 \uAD50\uC0AC\uAD00\uCC30\uAE30\uB85D \uBCC0\uD658 (Modal)",
      callback: () => {
        this.openConversionModal();
      }
    });
    this.addCommand({
      id: "convert-from-selection",
      name: "\uC120\uD0DD \uC601\uC5ED\uC5D0\uC11C \uAD50\uC0AC\uAD00\uCC30\uAE30\uB85D \uBCC0\uD658",
      editorCallback: (editor, view) => {
        const selection = editor.getSelection();
        if (!selection.trim()) {
          new import_obsidian.Notice("\uD14D\uC2A4\uD2B8\uB97C \uC120\uD0DD\uD574\uC8FC\uC138\uC694.");
          return;
        }
        this.processConversion(selection, this.settings.targetCharCount);
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        menu.addItem((item) => {
          item.setTitle("\uD559\uC0DD\uD65C\uB3D9 \u2192 \uAD50\uC0AC\uAD00\uCC30\uAE30\uB85D \uBCC0\uD658").setIcon("file-text").onClick(() => {
            this.openConversionModal();
          });
        });
      })
    );
  }
  async onunload() {
    console.log("Unloading Student Activity to Observation Plugin");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  openConversionModal() {
    if (!this.settings.apiKey) {
      new import_obsidian.Notice("API \uD0A4\uB97C \uC124\uC815\uD574\uC8FC\uC138\uC694. (\uC124\uC815 \u2192 \uD559\uC0DD\uD65C\uB3D9 \u2192 \uAD50\uC0AC\uAD00\uCC30\uAE30\uB85D \uBCC0\uD658)");
      return;
    }
    new InputModal(this.app, this, (data, charCount) => {
      this.processConversion(data, charCount);
    }).open();
  }
  async processConversion(data, targetCharCount) {
    const activities = parseTSV(data);
    if (activities.length === 0) {
      new import_obsidian.Notice("\uBCC0\uD658\uD560 \uB370\uC774\uD130\uAC00 \uC5C6\uC2B5\uB2C8\uB2E4.");
      return;
    }
    const progressModal = new ProgressModal(this.app);
    progressModal.open();
    const records = [];
    let errorCount = 0;
    for (let i = 0; i < activities.length; i++) {
      const activity = activities[i];
      progressModal.updateProgress(i + 1, activities.length, activity.studentName);
      try {
        let observation;
        switch (this.settings.apiProvider) {
          case "openai":
            observation = await callOpenAI(
              this.settings.apiKey,
              this.settings.modelId || DEFAULT_MODELS.openai,
              activity,
              targetCharCount
            );
            break;
          case "claude":
            observation = await callClaude(
              this.settings.apiKey,
              this.settings.modelId || DEFAULT_MODELS.claude,
              activity,
              targetCharCount
            );
            break;
          case "gemini":
            observation = await callGemini(
              this.settings.apiKey,
              this.settings.modelId || DEFAULT_MODELS.gemini,
              activity,
              targetCharCount
            );
            break;
          case "grok":
            observation = await callGrok(
              this.settings.apiKey,
              this.settings.modelId || DEFAULT_MODELS.grok,
              activity,
              targetCharCount
            );
            break;
          default:
            throw new Error(`\uC9C0\uC6D0\uD558\uC9C0 \uC54A\uB294 AI \uC81C\uACF5\uC790: ${this.settings.apiProvider}`);
        }
        records.push({
          studentId: activity.studentId,
          studentName: activity.studentName,
          activityContent: activity.activityContent,
          observation,
          charCount: countChars(observation),
          byteCount: countBytes(observation)
        });
      } catch (error) {
        console.error(`Error processing ${activity.studentName}:`, error);
        errorCount++;
        records.push({
          studentId: activity.studentId,
          studentName: activity.studentName,
          activityContent: activity.activityContent,
          observation: `[\uBCC0\uD658 \uC2E4\uD328: ${error instanceof Error ? error.message : "\uC54C \uC218 \uC5C6\uB294 \uC624\uB958"}]`,
          charCount: 0,
          byteCount: 0
        });
      }
      if (i < activities.length - 1) {
        await new Promise((resolve) => setTimeout(resolve, 500));
      }
    }
    progressModal.markLastStudentComplete();
    progressModal.close();
    await this.createResultNote(records);
    if (errorCount > 0) {
      new import_obsidian.Notice(`\uBCC0\uD658 \uC644\uB8CC! (${records.length - errorCount}\uBA85 \uC131\uACF5, ${errorCount}\uBA85 \uC2E4\uD328)`);
    } else {
      new import_obsidian.Notice(`${records.length}\uBA85\uC758 \uAD50\uC0AC\uAD00\uCC30\uAE30\uB85D \uBCC0\uD658 \uC644\uB8CC!`);
    }
  }
  async createResultNote(records) {
    const now = new Date();
    const dateStr = now.toISOString().slice(0, 10);
    const timeStr = now.toTimeString().slice(0, 5).replace(":", "");
    const fileName = `\uAD50\uC0AC\uAD00\uCC30\uAE30\uB85D_${dateStr}_${timeStr}.md`;
    let filePath = fileName;
    if (this.settings.outputFolder) {
      const folder = this.app.vault.getAbstractFileByPath(this.settings.outputFolder);
      if (!folder) {
        await this.app.vault.createFolder(this.settings.outputFolder);
      }
      filePath = `${this.settings.outputFolder}/${fileName}`;
    }
    const tsvData = generateTSVData(records);
    const encodedTSV = Buffer.from(tsvData).toString("base64");
    const content = `# \uAD50\uC0AC\uAD00\uCC30\uAE30\uB85D \uBCC0\uD658 \uACB0\uACFC

\uC0DD\uC131\uC77C\uC2DC: ${now.toLocaleString("ko-KR")}
\uCD1D \uC778\uC6D0: ${records.length}\uBA85

## \uD83D\uDCCB \uAD6C\uAE00 \uC2A4\uD504\uB808\uB4DC\uC2DC\uD2B8\uB85C \uBCF5\uC0AC

<div class="student-activity-copy-section">
<button class="student-activity-copy-btn" data-tsv="${encodedTSV}">
\uD83D\uDCCB \uD074\uB9AD\uD558\uC5EC \uBCF5\uC0AC\uD558\uAE30
</button>
<span class="copy-status"></span>
</div>

> \uC704 \uBC84\uD2BC\uC744 \uD074\uB9AD\uD558\uBA74 TSV \uB370\uC774\uD130\uAC00 \uD074\uB9BD\uBCF4\uB4DC\uC5D0 \uBCF5\uC0AC\uB429\uB2C8\uB2E4.
> \uAD6C\uAE00 \uC2A4\uD504\uB808\uB4DC\uC2DC\uD2B8\uC5D0\uC11C Ctrl+V\uB85C \uBD99\uC5EC\uB123\uC73C\uBA74 \uC5F4\uC774 \uC790\uB3D9\uC73C\uB85C \uAD6C\uBD84\uB429\uB2C8\uB2E4.

---

## \uACB0\uACFC \uD14C\uC774\uBE14

${generateMarkdownTable(records)}

## \uD1B5\uACC4

| \uD56D\uBAA9 | \uAC12 |
|------|-----|
| \uCD1D \uC778\uC6D0 | ${records.length}\uBA85 |
| \uD3C9\uADE0 \uAE00\uC790 \uC218 | ${Math.round(records.reduce((sum, r) => sum + r.charCount, 0) / records.length)}\uC790 |
| \uD3C9\uADE0 \uBC14\uC774\uD2B8 \uC218 | ${Math.round(records.reduce((sum, r) => sum + r.byteCount, 0) / records.length)} \uBC14\uC774\uD2B8 |
`;
    const file = await this.app.vault.create(filePath, content);
    const leaf = this.app.workspace.getLeaf(false);
    await leaf.openFile(file);
    this.registerCopyButtonHandler();
  }
  registerCopyButtonHandler() {
    setTimeout(() => {
      const copyButtons = document.querySelectorAll(".student-activity-copy-btn");
      copyButtons.forEach((btn) => {
        if (btn.hasAttribute("data-listener-attached"))
          return;
        btn.setAttribute("data-listener-attached", "true");
        btn.addEventListener("click", async (e) => {
          const button = e.target;
          const encodedTSV = button.getAttribute("data-tsv");
          if (!encodedTSV)
            return;
          try {
            const tsvData = Buffer.from(encodedTSV, "base64").toString("utf-8");
            await navigator.clipboard.writeText(tsvData);
            const originalText = button.textContent;
            button.textContent = "\u2705 \uBCF5\uC0AC \uC644\uB8CC!";
            button.classList.add("copied");
            new import_obsidian.Notice("\uD83D\uDCCB \uD074\uB9BD\uBCF4\uB4DC\uC5D0 \uBCF5\uC0AC\uB418\uC5C8\uC2B5\uB2C8\uB2E4! \uAD6C\uAE00 \uC2A4\uD504\uB808\uB4DC\uC2DC\uD2B8\uC5D0 \uBD99\uC5EC\uB123\uAE30(Ctrl+V)\uD558\uC138\uC694.");
            setTimeout(() => {
              button.textContent = originalText;
              button.classList.remove("copied");
            }, 2e3);
          } catch (error) {
            new import_obsidian.Notice("\uBCF5\uC0AC \uC2E4\uD328: " + (error instanceof Error ? error.message : "\uC54C \uC218 \uC5C6\uB294 \uC624\uB958"));
          }
        });
      });
    }, 500);
  }
};
